sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wyh989795


  wechat:
    appid: wx10f6b28d88bf2e63
    secret: f2d1c3d18ab6cc58dfb30cdac76cc825

